# Generated by Django 4.2.14 on 2025-11-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={},
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
