# Generated by Django 4.2.14 on 2025-11-27 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizador', '0004_cliente_razon_social_cliente_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='creada_por_invitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='email_invitado',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado a este ítem.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('giro', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descuento_maximo_vendedores', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje máximo de descuento permitido a los vendedores.', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pymes_propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pyme',
                'verbose_name_plural': 'Pymes',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM_OWNER', 'Dueño del sistema'), ('PYME_OWNER', 'Dueño de pyme'), ('SELLER', 'Vendedor')], max_length=20)),
                ('descuento_maximo_personal', models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, este límite aplica sólo a este vendedor.', max_digits=5, null=True)),
                ('pyme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='cotizador.pyme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='pyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cotizador.pyme'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='cotizador.pyme'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pyme',
            field=models.ForeignKey(blank=True, help_text='Pyme dueña del producto. Si está vacío, se considera genérico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizador.pyme'),
        ),
    ]
