# Generated by Django 4.2.14 on 2025-11-27 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizador', '0005_alter_cotizacion_options_remove_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='representante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pyme',
            name='servicios',
            field=models.TextField(blank=True, help_text='Descripción de los servicios o productos que ofrece la Pyme.'),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pymes_propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
