# Generated by Django 4.2.14 on 2025-12-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_pyme_representante_pyme_servicios_alter_pyme_dueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pymes/logos/'),
        ),
    ]
