# Generated by Django 4.2.14 on 2025-12-06 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizador', '0007_pyme_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='recomendado_por_vendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor_recomendador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_recomendadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
