# Generated by Django 4.2.14 on 2025-12-11 15:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_cotizacion_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Úsalo para otro impuesto si aplica. Para servicios sin impuesto, puedes dejarlo vacío o en 0.', max_digits=5, null=True, verbose_name='Segundo impuesto (%)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.0'), help_text='Impuesto principal (por ejemplo IVA).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('software', 'Software'), ('servicio', 'Servicio'), ('hardware', 'Hardware'), ('otros', 'Otros')], max_length=20),
        ),
    ]
