# Generated by Django 4.2.14 on 2025-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_producto_impuesto_adicional_alter_cotizacion_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('SYSTEM_OWNER', 'Dueño del sistema'), ('PYME_OWNER', 'Dueño de pyme'), ('SELLER', 'Vendedor'), ('INVITED', 'Invitado')], max_length=20),
        ),
    ]
